
import React, { forwardRef } from 'react';

interface PdfPreviewProps {
  content: string;
}

export const PdfPreview = forwardRef<HTMLDivElement, PdfPreviewProps>(({ content }, ref) => {
    const lines = content.split('\n');
    const title = lines[0] || 'My Story';
    const body = lines.slice(1).join('\n');

    const formattedBody = body.split('\n').filter(p => p.trim() !== '').map((paragraph, index) => (
        <p style={{ marginBottom: '1em' }} key={index}>
            {paragraph}
        </p>
    ));

    return (
        <div ref={ref} style={{ width: '210mm', minHeight:'297mm', position:'relative', padding: '20mm', boxSizing: 'border-box', background: 'white', color: 'black' }}>
            <h1 style={{ fontFamily: 'Georgia, serif', fontSize: '24pt', textAlign: 'center', marginBottom: '24px', hyphens:'auto', color: '#111827' }}>
                {title}
            </h1>
            <div style={{ fontFamily: 'Georgia, serif', fontSize: '12pt', lineHeight: '1.6', textAlign: 'justify', hyphens:'auto', color: '#1f2937' }}>
                {formattedBody}
            </div>
            <div style={{ position: 'absolute', bottom: '10mm', fontSize: '9pt', color: '#6b7280', width: 'calc(100% - 40mm)', textAlign: 'center' }}>
                Generated by AI Story Studio
            </div>
        </div>
    );
});
